---
- hosts: k8snode
  become: yes

  tasks:
    - name: copy the join command 
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 077
    - name: Join the worker node
      become: yes 
      command: sh /tmp/kubernetes_join_command
      register: join_or_not