---

- 

  hosts: all
  tasks:
    - name: update ubuntu system 
      apt:
        update_cache=yes
    - name: upload the kernal module
      modprobe:
        name: "{{item}}"
        state: present 
      with_items:
        - overlay
        - br_netfilter
    
    - name: turn sysctl parameters in /proc 
      sysctl:
        name: "{{items}}"
        value: '1'
        sysctl_set: yes
        state: present 
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward        
     